apiVersion: apps/v1
kind: Deployment

metadata:
   name: nwappv2-deploy
   labels:
      app: nwappv2
      version: v2

spec:
   replicas: 2
   selector:
      matchLabels:
         app: nwapp
         version: v2
   template:
      metadata:
         name: nwapp-pod
         labels:
            app: nwapp
            version: v2
      spec:
         containers:
         - name: nwapp
           image: chukmunnlee/northwind-app:v2
           imagePullPolicy: IfNotPresent
           ports:
           - containerPort: 3000
           env:
           - name: DB_HOST
             value: nwdb.myspace.svc.cluster.local
           - name: DB_USER
             valueFrom:
                secretKeyRef:
                   name: nwapp-secret
                   key: DB_USER
           - name: DB_PASSWORD
             valueFrom:
                secretKeyRef:
                   name: nwapp-secret
                   key: DB_PASSWORD
           livenessProbe: 
               httpGet:
                  path: /health
                  port: 3000

---

apiVersion: v1
kind: Service
metadata:
   name: nwappv2-svc

spec:
   type: NodePort
   selector:
      app: nwapp
      version: v2
   ports:
   - port: 8080
     targetPort: 3000
